[2022-05-15 22:38:42.704] [remoteagent] [info] Extension host agent started.
[2022-05-15 22:38:44.235] [remoteagent] [info] [127.0.0.1][87fd6ad2][ManagementConnection] New connection established.
[2022-05-15 22:38:44.983] [remoteagent] [info] [127.0.0.1][34b72c20][ExtensionHostConnection] New connection established.
[2022-05-15 22:38:48.642] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2022-05-15 22:38:52.404] [remoteagent] [error] ptyHost was unable to resolve shell environment {}
[2022-05-15 22:38:52.405] [remoteagent] [error] RequestService#request (node) resolving shell environment failed {}
[2022-05-15 22:38:52.406] [remoteagent] [error] ExtensionHostConnection#buildUserEnvironment resolving shell environment failed {}
[2022-05-15 22:38:52.443] [remoteagent] [info] [127.0.0.1][34b72c20][ExtensionHostConnection] <117> Launched Extension Host Process.
[2022-05-15 22:38:54.279] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: inotify_add_watch on '/home/jtorne2/.vscode-server/data/logs/20220416T102713/exthost1/output_logging_20220416T102726' failed: No such file or directory (EUNKNOWN) (path: /home/jtorne2)
[2022-05-15 22:38:54.280] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: inotify_add_watch on '/home/jtorne2/.vscode-server/data/logs/20220416T102713/exthost1/output_logging_20220416T102726' failed: No such file or directory
[2022-05-15 22:38:56.049] [remoteagent] [error] ExtensionHostConnection#buildUserEnvironment resolving shell environment failed {}
[2022-05-15 23:35:54.354] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: std::bad_alloc (EUNKNOWN) (path: /home/jtorne2)
[2022-05-15 23:35:54.357] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: std::bad_alloc
[2022-05-15 23:40:13.772] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: std::bad_alloc (EUNKNOWN) (path: /home/jtorne2)
[2022-05-15 23:40:13.773] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: std::bad_alloc
[2022-05-15 23:44:12.676] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: std::bad_alloc (EUNKNOWN) (path: /home/jtorne2)
[2022-05-15 23:44:12.677] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: std::bad_alloc
[2022-05-15 23:45:24.361] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: std::bad_alloc (EUNKNOWN) (path: /home/jtorne2)
[2022-05-15 23:45:24.362] [remoteagent] [error] [File Watcher (universal)] restarting watcher after error: std::bad_alloc
[2022-05-15 23:46:57.991] [remoteagent] [error] [File Watcher (parcel)] Unexpected error: std::bad_alloc (EUNKNOWN) (path: /home/jtorne2)
[2022-05-15 23:46:57.991] [remoteagent] [error] [File Watcher (universal)] gave up attempting to restart watcher after error: std::bad_alloc
[2022-05-16 02:55:34.485] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2022-05-16 08:07:15.753] [remoteagent] [info] [127.0.0.1][34b72c20][ExtensionHostConnection] The client has reconnected.
[2022-05-16 08:07:15.776] [remoteagent] [info] [127.0.0.1][87fd6ad2][ManagementConnection] The client has reconnected.
[2022-05-16 15:39:26.799] [remoteagent] [info] [127.0.0.1][87fd6ad2][ManagementConnection] The client has reconnected.
[2022-05-16 15:39:27.415] [remoteagent] [info] [127.0.0.1][34b72c20][ExtensionHostConnection] The client has reconnected.
[2022-05-16 16:49:39.085] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2022-05-16 18:55:32.450] [remoteagent] [info] [127.0.0.1][87fd6ad2][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[2022-05-16 18:55:33.725] [remoteagent] [info] [127.0.0.1][34b72c20][ExtensionHostConnection] <117> Extension Host Process exited with code: 0, signal: null.
